version: '3.9'
name: flask-chatgpt

services:
  postgres:
    image: postgres:11-alpine
    container_name: postgres
    shm_size: 4g
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
    expose:
      - "5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:rw
  app:
    container_name: app
    build: ./app/
    depends_on: 
      - postgres
    env_file:
      - .env
    ports:
      - "127.0.0.1:5000:5000"